name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend:
    if: ${{ hashFiles('ModGoviya/backend/package.json') != '' }}
    name: Backend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ModGoviya/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm ci

      - name: Run security audit (non-blocking)
        run: npm audit --production --audit-level=high || true

      - name: Verify backend entry exists
        run: node -e "require('fs').accessSync('server.js'); console.log('server.js found')"

  frontend:
    if: ${{ hashFiles('ModGoviya/frontend/package.json') != '' }}
    name: Frontend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ModGoviya/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: build
