name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend:
    name: Backend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ModGoviya_farmer_assistance_MERN_platform/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ModGoviya_farmer_assistance_MERN_platform/backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Security audit (non-blocking)
        run: npm audit --production --audit-level=high || true

      - name: Verify backend entry exists
        run: node -e "require('fs').accessSync('server.js'); console.log('server.js found')"

  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ModGoviya_farmer_assistance_MERN_platform/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ModGoviya_farmer_assistance_MERN_platform/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ModGoviya_farmer_assistance_MERN_platform/build
