name: CI

on:
  push:
    branches: ["**"]
    paths:
      - 'backend/**'
      - 'public/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'
  pull_request:
    branches: ["**"]
    paths:
      - 'backend/**'
      - 'public/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'

jobs:
  backend:
    name: Backend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Listing repository contents:"
          ls -R ..
          echo "Checking for package-lock.json in backend:"
          ls -l package-lock.json || echo "backend/package-lock.json not found"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
        continue-on-error: true

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run ESLint
        run: npm run lint
        if: success()

      - name: Security audit (non-blocking)
        run: npm audit --production --audit-level=high || true

      - name: Verify backend entry exists
        run: node -e "require('fs').accessSync('server.js'); console.log('server.js found')"

      - name: Run tests
        run: npm test
        if: success()

  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Listing repository contents:"
          ls -R .
          echo "Checking for package-lock.json in root:"
          ls -l package-lock.json || echo "package-lock.json not found"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
        continue-on-error: true

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run ESLint
        run: npm run lint
        if: success()

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: build
